### ISSUE TITLE
flatpak cz.krupkat.Xpano - cant not load files, missing org.freedesktop.portal.FileChooser?

### ISSUE THREAD

**Issue by Clind99** [krupkat/xpano#115]
I encountered this bug running the flatpak version on linux (gentoo profile amd64/17.1/desktop (stable))
Xpano                             cz.krupkat.Xpano                                           0.17.0              stable                system

Looks like a dependancy is missing or an external call is broken ?
![Screenshot_2023-11-20_14-23-22](https://github.com/krupkat/xpano/assets/26350023/f47dd8c6-4fd3-48c6-9751-805ede4ac8fb)

**Comment by krupkat** [comment]
Hello, thanks for the report!

Can you please confirm if you have any of these portal packages installed? If not that could be the fix.

https://packages.gentoo.org/packages/search?q=xdg-desktop-portal

**Comment by Clind99** [comment]
I have sys-apps/xdg-desktop-portal ver 1.16.0-r1 installed
I'll tried to install sys-apps/xdg-desktop-portal-gtk as well but nothing's changed ...

**Comment by krupkat** [comment]
Strange, you can also check if the portal is running when before launching Xpano

`ps -ax | grep portal` should show some portal implementation running, if it's not , it should be enabled somehow as a service

**Comment by Clind99** [comment]
I get these running continuously
clind     4272  0.0  0.0 531664  8324 ?        Sl   09:30   0:00 /usr/libexec/xdg-desktop-portal
clind     4278  0.0  0.0 605796  6024 ?        Sl   09:30   0:00 /usr/libexec/xdg-document-portal

The plot thickens ! :D

**Comment by Clind99** [comment]
Ok solved : 
I had to install sys-apps/xdg-desktop-portal-gtk AND restart my system for it to work.

Flatpak packages not being manage by portage (general distro dependencies management) I guess it was not pulled as needed.
Sorry for the noise, I guess you can change the status to fixed ?

Thanks for your time !

**Comment by krupkat** [comment]
No worries, happy you solved it, maybe it can help someone else.

This should honestly be better documented on flatpak website, it is not mentioned in the install instructions and buried quite deep in the docs: https://docs.flatpak.org/en/latest/desktop-integration.html#portals
