### ISSUE TITLE
Show stitch error code in gui

### ISSUE THREAD

**Issue by krupkat** [krupkat/xpano#17]
The error code from the OpenCV stitch function isn't being propagated to the gui.

Here is the call to the OpenCV function:
[Code location](https://github.com/krupkat/xpano/blob/6fce4f8c0844b4c67f1d003765c09740195d427b/xpano/algorithm/algorithm.cc#L107)

Propagate the value to the tooltip_message_ here:
[Code location](https://github.com/krupkat/xpano/blob/6fce4f8c0844b4c67f1d003765c09740195d427b/xpano/gui/pano_gui.cc#L345)

**Comment by GhostVaibhav** [comment]
Can I work on this issue?

**Comment by krupkat** [comment]
Great, feel free!

Thanks.
