### ISSUE TITLE
Async license loading

### ISSUE THREAD

**Issue by krupkat** [krupkat/xpano#22]
The license files are currently being loaded before the start of the main gui: [Code location](https://github.com/krupkat/xpano/blob/6fce4f8c0844b4c67f1d003765c09740195d427b/xpano/main.cc#L83).

- Measure the impact / delay between launch and gui first showing up
- Implement async loading of the files

**Comment by GhostVaibhav** [comment]
Can we use std::async in this or do we have to figure out an implementation using pthreads?

**Comment by krupkat** [comment]
std::async is good

There is also a thread pool in stitcher_pipeline, but I think it doesn't make sense to use that one as this is a one off task, not related to the stitching.

**Comment by krupkat** [comment]
Thanks for checking this! From the measurement it seems not significant enough to warrant the code change... although this could be tricky to measure right, since the files are likely in ram / some cache from the first launch on. Also on hdd it could be more pronounced.

Maybe you can upload your code in a branch in your fork so we can use it later if needed? I can also check your implementation tomorrow to see if there is anything wrong.

**Comment by GhostVaibhav** [comment]
Yes, true. Thanks in advance for checking my code; indeed, I have committed my code https://github.com/GhostVaibhav/xpano/commit/ee5078686cf1e50ef3c068bc1d54cb215e7dc4e9 here.
