### ISSUE TITLE
Show buton does not show anything after importing 2 images

### ISSUE THREAD

**Issue by Clind99** [krupkat/xpano#64]
**Initial situation**
I imported 2 png files via the "Import images : Multiple files" button

- Their thumbnails display correctly in the bottom "film strip" style area
- In "list of pano" I have one pano titled "0,1" and a "show button
- Hovering the "show" button displays one more instance of the 2 thumbnails attach to my cursor position
- the right pano area is void

**THE BUG :** 
Pushing the show buttons shows nothing
I have a "failed to stitch pano 0" with ERR_NEED_MORE_IMGS

ADDITIONAL INFO
- displaying debug info show a "matched" list with a functional "show" button that shows "184 inliers" displayed in green on the image

**Desktop infos:**
 - OS: Gentoo - kernel 5.10.76-gentoo-r1 - profile 17.1 desktop (stable)
 - Version: xpano 0.9.0
 - Method of installation: flatpak

**ONE TIME** link to images
82.64.103.11/online/f.php?h=1OunIyVs
82.64.103.11/online/f.php?h=1OunIyVs

**Comment by krupkat** [comment]
Thanks for filing the bug, I'll investigate.

The two links included are the same, I only got the first image.

**Comment by Clind99** [comment]
http://82.64.103.11/online/f.php?h=021AEjyP&d=1
ssssorry here's the 2nd one
