### ISSUE TITLE
unable to launch on OSX, dylib error

### ISSUE THREAD

**Issue by Dero99** [krupkat/xpano#75]
**Bug description**
Cloned latest release (today) and installed on OSX 13.1 with no errors and 48 tests pass.

Launching ~/xpano/install/bin/Xpano aborts due to dylib files not found.

fleming@Flemings-Mac-mini ~ % /Users/fleming/Documents/GitHub/xpano/install/bin/Xpano ; exit;
dyld[56853]: Library not loaded: @rpath/libopencv_imgcodecs.407.dylib
  Referenced from: <E4044513-9D07-30CA-85B3-97D8772527CE> /Users/fleming/Documents/GitHub/xpano/install/bin/Xpano
  Reason: tried: '/System/Volumes/Preboot/Cryptexes/OS@rpath/libopencv_imgcodecs.407.dylib' (no such file), '/usr/local/lib/libopencv_imgcodecs.407.dylib' (no such file), '/usr/lib/libopencv_imgcodecs.407.dylib' (no such file, not in dyld cache)
zsh: abort      /Users/fleming/Documents/GitHub/xpano/install/bin/Xpano

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

These files are in ~/xpano/opencv/install/lib/cmake.  Copying the aliases to /usr/local/lib did not fix issue.

**Comment by krupkat** [comment]
I don't have access to a Mac atm, but from memory you can try:

```
DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:/path/to/dir/with/opencv/dylib/files" ~/xpano/install/bin/Xpano
```

**Comment by Dero99** [comment]
HiSorry, same result. DarrellSent from my iPadOn Apr 8, 2023, at 12:32 PM, Tomáš Krupka ***@***.***> wrote:﻿
I don't have access to a Mac atm, but from memory you can try:
DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:/path/to/dir/with/opencv/dylib/files" ~/xpano/install/bin/Xpano

**Comment by krupkat** [comment]
Can you try launching directly `~/xpano/build/Xpano`?

Alternatively, you can modify `misc\build\build-macos-12.sh` to build static library, on line 16:

```
cmake -B build -DBUILD_SHARED_LIBS=OFF \
```

**Comment by Dero99** [comment]
HiUsing static libs allows App to run. ThanksDarrellSent from my iPadOn Apr 9, 2023, at 8:30 AM, Tomáš Krupka ***@***.***> wrote:﻿
Can you try launching directly ~/xpano/build/Xpano?
Alternatively, you can modify misc\build\build-macos-12.sh to build static library, on line 16:
cmake -B build -DBUILD_SHARED_LIBS=OFF \

**Comment by krupkat** [comment]
Fixed by https://github.com/krupkat/xpano/commit/001a4f2483005ebaa5b05bd854665bd655e175e2
