### ISSUE TITLE
Seamless blending

### ISSUE THREAD

**Issue by prokoudine** [krupkat/xpano#76]
It doesn't look like Xpano is capable of seamless blending right now.

It becomes obvious when there's clear sky in the photos. Here is how hugin blends:

![image](https://user-images.githubusercontent.com/57467/230771814-0b57cc3a-2216-4fa5-91d4-a2ea7d4c21d7.png)

Here is what Xpano does:

![Screenshot from 2023-04-09 14-09-31](https://user-images.githubusercontent.com/57467/230771857-98d337c0-810c-49e5-9b2a-aed2062613ac.png)

You can clearly see darker patches of sky in the latter case.

There are multiple options how to deal with that. Enblend seems unmaintained, but https://horman.net/multiblend/ keeps getting updates apparently.

And then there's also https://github.com/weltyj/SkyFill to fill missing parts of the sky, if you are interested.

**Comment by krupkat** [comment]
Thanks for the report and the tip for MultiBlend, that looks very nice and could be worth having an additional dependency.

Regarding SkyFill, I'm looking for a fill algorithm that would work for everything ideally with no user interaction (high hopes :)).

todo: test MultiBlend
images to test on: https://discuss.pixls.us/t/lack-of-detail-in-xpano-stitched-images/36523/3

**Comment by krupkat** [comment]
I have managed to test Xpano + Multiblend and the results look nice, I'll take a look at integrating it in the next version.

Example image:
https://discuss.pixls.us/t/lack-of-detail-in-xpano-stitched-images/36523/6?u=krupkat

**Comment by pedrorrodriguez** [comment]
Is gamma undone before stitching in xpano?

**Comment by pedrorrodriguez** [comment]
According to Aurelien Pierre, the developer of Ansel, and many color modules in darktable it should be the first step, before doing anything.

**Comment by krupkat** [comment]
There is a working version of the Multiblend integration here:
https://github.com/krupkat/xpano/tree/feature-multiblend

The details are preserved much better in the output and also the smoothness is better.

On the other hand there is a bit worse seam estimation. It could be possible to combine the seam estimation from OpenCV and the rest from Multiblend in the future.

Todo before release:
- integrate spdlog to Multiblend for unified logging
- disable build of Multiblend if SSE instructions are not available (e.g. mac m1) 
  - use [simde](https://github.com/simd-everywhere/simde) to fix later
- add a test

**Comment by krupkat** [comment]
> According to Aurelien Pierre, the developer of Ansel, and many color modules in darktable it should be the first step, before doing anything.

I need to give it some more thought. Note that ideally the stitching algorithm is doing as little modification of pixel values as possible - when the exposure is consistent across images (this is of course not always true).

Could you please link some more details about this process?

**Comment by krupkat** [comment]
I'll make a release with #94 in a bit. Feel free to reopen this issue with further suggestions / examples.
