### ISSUE TITLE
Enhancement: recognize TIFF files with .tif or .TIF extension

### ISSUE THREAD

**Issue by sjsepan3** [krupkat/xpano#80]
**Bug description**
-AnotherRawTherapee exports TIFF files with '.tif'
-.tif or .TIF not visible with default filter; I have to switch to 'all' to find
-.tif or .TIF not processed with 'all files' filter; when selected, images are not loaded
-if I rename extensions to .tiff or .TIFF, the files are loaded and processed

**Desktop (please complete the following information):**
 - OS: 
  Linux Mint
 - Version: 
  app: 0.11.0
  os: 21.1
 - Method of installation:
 APT repository on launchpad

**Comment by krupkat** [comment]
Hello @sjsepan3 and thanks for the report!

I already merged a fix for this a few days ago: https://github.com/krupkat/xpano/pull/79
It will be released today / in a couple of days

**Comment by sjsepan3** [comment]
> Hello @sjsepan3 and thanks for the report!
> 
> I already merged a fix for this a few days ago: #79 It will be released today / in a couple of days

Awesome! I didn't see an issue about this already, so I wrote this one. Looking forward to it, and glad you were already on top of this one. Thanks for the app -- it's as easy to use as MS ICE was.
