### ISSUE TITLE
Add cli ability

### ISSUE THREAD

**Issue by robbymilo** [krupkat/xpano#83]
It would be great to use Xpano via the command line to enable scripting of panoramas.

This would also enable Xpano to be used as a darktable lua script. For example: https://github.com/darktable-org/lua-scripts/blob/master/contrib/hugin.lua allows you to select multiple images, which are then exported to a /tmp dir, imported and stitched by hugin, and the resulting panorama then is imported to darktable.

**Comment by krupkat** [comment]
A darktable plugin would be quite nice indeed, thanks for the tip!

I started working on the cli addition.
