### ISSUE TITLE
PKGBUILD proposal for Arch linux

### ISSUE THREAD

**Issue by sguyader** [krupkat/xpano#85]
Please find below a tentative PKGBUILD for Arch users. Note that the `ctest` command in the `check()` section is commented out, until test #20 is fixed.

```
# Maintainer: Sébastien Guyader <sguyader@gmail.com>

_pkgname=xpano
pkgname="$_pkgname-git"
pkgver=0.12.0.r1.g4d9afc6
pkgrel=1
pkgdesc="Automated photo stitching tool, with focus on simplicity and ease of use"
arch=('x86_64')
url='https://github.com/krupkat/xpano'
license=('GPL3')
depends=('gtk3' 'opencv>=4.4.0' 'sdl2' 'spdlog' 'catch2v3')
makedepends=('cmake' 'git')
provides=("$_pkgname")
conflicts=("$_pkgname")
source=('xpano::git+https://github.com/krupkat/xpano.git'
		'alpaca::git+https://github.com/p-ranav/alpaca.git'
		'imgui::git+https://github.com/krupkat/imgui.git'
		'nativefiledialog-extended::git+https://github.com/btzy/nativefiledialog-extended.git'
		'thread-pool::git+https://github.com/krupkat/thread-pool.git'
		)
md5sums=('SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP')

pkgver(){
	cd $_pkgname
	git describe --long --tags --abbrev=7 | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g'
}

prepare() {
	git -C xpano submodule init
	local _submodule
	for _submodule in alpaca imgui nativefiledialog-extended thread-pool
	do
		git -C xpano config --local submodule.external/${_submodule}.url "$srcdir/${_submodule}"
	done
	git -C xpano -c protocol.file.allow='always' submodule update
}

build() {
	cmake -B build -S $_pkgname \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DBUILD_TESTING=ON \
		-DCMAKE_EXPORT_COMPILE_COMMANDS=OFF
	cmake --build build -j $(nproc)
}

check() {
	cd build
	#ctest
}

package() {
	DESTDIR="$pkgdir" cmake --install build
}
````

**Comment by krupkat** [comment]
This is great work, thanks a lot!

**Comment by sguyader** [comment]
On the Arch AUR forum, I was advised to remove packages from the build() section packages that are already available as packages for Arch. It is the case for `imgui` and `nativedialog-extended` (the latter package is called `libnfd` for Arch).
I'll report my progress here.

**Comment by krupkat** [comment]
Thanks a lot!

`libnfd` could work, but it seems to be outdated?
1.0.0 in aur: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libnfd
1.0.2 in https://github.com/btzy/nativefiledialog-extended/releases
\+ there is no maintainer contact in the pkgbuild

for imgui I'm using a fork of the `docking` branch: https://github.com/krupkat/imgui/releases/tag/docking_v1.89.4_wip
this branch is not included in the tagged release, so not possible to use https://aur.archlinux.org/packages/imgui
\+ there is a fix for highdpi support on mac and linux (https://github.com/ocornut/imgui/issues/3757#issuecomment-1484739710)

**Comment by krupkat** [comment]
I have added a github action to upload a source archive including submodules, starting with [version 0.16.1](https://github.com/krupkat/xpano/releases/tag/v0.16.1).

I plan to use it to create a NixOS package, maybe it could be adopted for the arch package as well? It should be quite a bit simpler to build from this new tar.gz archive.

**Comment by krupkat** [comment]
https://aur.archlinux.org/packages/xpano-git
