### ISSUE TITLE
0.15: missing multiblend option on OSX arm

### ISSUE THREAD

**Issue by MStraeten** [krupkat/xpano#97]
the multiblend option is missing even there're no errors in the build output
![image](https://github.com/krupkat/xpano/assets/39386816/f4ea6287-28ca-49e0-91a2-a7fd12aef13a)

**Desktop (please complete the following information):**
 - OS: macOS Ventura
 - Version: 13.4
 - arm64
 - Method of installation: ./misc/build/build-macos-12.sh but in an macports environment

**Comment by MStraeten** [comment]
Apple silicon doesn’t support sse, so no bug …

**Comment by krupkat** [comment]
That is correct, I have created an issue for tracking: https://github.com/krupkat/multiblend/issues/24

**Comment by krupkat** [comment]
@MStraeten would you mind testing this on the arm cpu? It would be super helpful.
- https://github.com/krupkat/multiblend/pull/25
- there are build + test instructions included

No worries if it doesn't work, there are probably some issues. I'll look at borrowing a macbook next :)

**Comment by krupkat** [comment]
Multiblend should be available now, see the pull request with details on how to build.

I have tested on an ARM chromebook and it works well there.

**Comment by MStraeten** [comment]
confirmed with m1
